install.packages("VennDiagram")

library(VennDiagram)

setwd("C:\\Users\\dener\\Desktop\\LAST\\venn")

draw.quintuple.venn(area.vector = c(3730,
 						0,
 						0,
 						0,
 						0,
 						0,
 						0,
 						0,
 						0,
 						2398,
 						575,
 						169,
 						0,
 						0,
 						0,
 						155,
 						92,
 						53,
 						0,
 						0,
 						0,
 						99,
 						94,
 						9,
 						0,
 						6,
 						0,
 						2,
 						0,
 						6,
 						0),
 			category = c("INTRON", "EXON", "5'UTR", "3'UTR", "CDS"),
 			lty = "blank",
 			fill = c("skyblue", "pink1", "mediumorchid", "yellow", "orange"),
 			direct.area = T)

draw.quad.venn(area.vector=c( 3730,
 					155,
 					2398,
 					0,
 					101,
					2,
 					53,
 					263,
 					0,
 					852,
 					15,
 					0,
 					0,
 					0,
 					0), 
			category = c("5'", "3'", "Intron", "Exon"),
			theme(text = element_text(size=18)),
			lty = "solid",
			fill = c("orange", "red", "green", "blue"),
			direct.area = T)